ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/lidar
    frame_id: laser_frame
    baudrate: 512000
    lidar_type: 0
    device_type: 0
    sample_rate: 20
    abnormal_check_count: 4
    fixed_resolution: false
    reversion: true
    inverted: true
    auto_reconnect: true
    isSingleChannel: false
    intensity: false
    ignore_array: ""
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 16.0
    range_min: 0.20
    frequency: 10.0
    invalid_range_is_inf: true

